FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY ./ ./

RUN PBG_INSTALL_CPP=1 pip install -e . --no-cache-dir
RUN pip install -r requirements.txt --no-cache-dir

ENV PYTHONUNBUFFERED=1
CMD ["python3", "-u", "handler.py"]